apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <NAME>
spec:
  type: state.azure.blobstorage
  # Supports v1 and v2. Users should always use v2 by default. There is no
  # migration path from v1 to v2, see `versioning` below.
  version: v2
  metadata:
  - name: accountName
    value: "mystorage911"
  - name: accountKey
    value: "d1/SU4qwf1ts+2nX48adtTZW0T57QVDWSQboaMMEOpI2+boRUrzbyHcNs69jPxU2beq/MGE+SP/B+AStU9t8yA=="
  - name: containerName
    value: "mystate"