apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <NAME>
spec:
  type: state.azure.blobstorage
  # Supports v1 and v2. Users should always use v2 by default. There is no
  # migration path from v1 to v2, see `versioning` below.
  version: v2
  metadata:
  - name: accountName
    value: "STORAGE_ACCOUNT_NAME"
  - name: accountKey
    value: "STORAGE_ACCOUNT_KEY"
  - name: containerName
    value: "STORAGE_ACCOUNT_CONTAINER_NAME"